export const ALPHA: items = [
  { name: 'APPLE', flag: '🍎', symbol: 'A-' },
  { name: 'BALL', flag: '⚽', symbol: 'B-' },
  { name: 'CAT', flag: '🐈‍⬛', symbol: 'C-' },
  { name: 'DOG', flag: '🐕', symbol: 'D-' },
  { name: 'ELEPHANT', flag: '🐘', symbol: 'E-' },
  { name: 'FISH', flag: '🐟', symbol: 'F-' },
  { name: 'GOAT', flag: '🐐', symbol: 'G-' },
  { name: 'HORSE', flag: '🐎', symbol: 'H-' },
  { name: 'ICE CREAM', flag: '🍦', symbol: 'I-' },
  { name: 'JUG', flag: '🏺', symbol: 'J-' },
  { name: 'KITE', flag: '🪁', symbol: 'K-' },
  { name: 'LION', flag: '🦁', symbol: 'L-' },
  { name: 'MONKEY', flag: '🐒', symbol: 'M-' },
  { name: 'NEST', flag: '🪹', symbol: 'N-' },
  { name: 'OWL', flag: '🦉', symbol: 'O-' },
  { name: 'PARROT', flag: '🦜', symbol: 'P-' },
  { name: 'QUEEN', flag: '👑', symbol: 'Q-' },
  { name: 'ROSE', flag: '🌹', symbol: 'R-' },
  { name: 'SHIP', flag: '🚢', symbol: 'S-' },
  { name: 'TIGER', flag: '🐅', symbol: 'T-' },
  { name: 'UMBRELLA', flag: '☂️', symbol: 'U-' },
  { name: 'VIOLIN', flag: '🎻', symbol: 'V-' },
  { name: 'WHALE', flag: '🐋', symbol: 'W-' },
  { name: 'X-MASS', flag: '🎄', symbol: 'X-' },
  { name: 'YAK', flag: '🐂', symbol: 'Y-' },
  { name: 'ZEBRA', flag: '🦓', symbol: 'Z-' }
];
